# Generated by Django 3.2.3 on 2021-05-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototicket',
            name='title',
            field=models.CharField(default='제목 추가입니다.', max_length=100),
            preserve_default=False,
        ),
    ]
