# Generated by Django 3.2.3 on 2021-05-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_phototicket_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phototicket',
            name='message',
        ),
    ]
