# Generated by Django 3.2.3 on 2021-05-21 04:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_phototicket_poster_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendAlgo',
            new_name='RecommendAlgoScore',
        ),
    ]
