# Generated by Django 3.2.3 on 2021-05-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_phototicket_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.TextField(default='profile_images/2021/05/21/default_profile.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='nickname',
            field=models.CharField(default='닉네임', max_length=50),
            preserve_default=False,
        ),
    ]
