# Generated by Django 3.2.3 on 2021-05-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_recommendalgo_recommendalgoscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendalgoscore',
            name='score',
        ),
        migrations.AddField(
            model_name='recommendalgoscore',
            name='rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
