# Generated by Django 3.2.3 on 2021-05-21 08:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='static/accounts/default_profile.jpg', upload_to='profile_images/%Y/%m/%d/'),
        ),
    ]
