# Generated by Django 3.2.3 on 2021-05-21 08:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='accounts/default_profile.jpg', upload_to='profile_images/%Y/%m/%d/'),
        ),
    ]
